apiVersion: v1
kind: Namespace
metadata:
  name: collector
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/part-of: falco-ctf
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
