apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: collector
  labels:
    {{- include "falco-ctf-common.labels" (dict "name" "collector" "managedBy" .Release.Service) | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: collector
  ports:
    - name: http
      port: 80
      targetPort: 8000
