apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scoreboard-data
  namespace: scoreboard
  labels:
    app.kubernetes.io/name: scoreboard
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
