{{- if .Values.challenge.fixtures }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: challenge-fixtures
  namespace: {{ include "ctf-user.namespace" . }}
  labels:
    {{- include "ctf-user.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.challenge.fixtures }}
  {{ $name }}: |-
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
