apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/name: auth-policy
  app.kubernetes.io/part-of: falco-ctf
  app.kubernetes.io/managed-by: kustomize
images:
  - name: docker.io/falco-ctf/auth-policy
    newTag: dev
